<a href="https://colab.research.google.com/github/hemantnr/probable-broccoli/blob/main/LinReg_model_Hemanth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [27]:
data = pd.read_excel('/content/NMC_cycling_data.xlsx', skiprows = 2)

In [28]:
data.head()

,Unnamed: 0,Ambient temperature,Discharging current,Depth of discharge,Average charging current,State of Health,dSOH/dNeq
0,cell_name,NaN,NaN,NaN,NaN,NaN,NaN
1,B2,15.0,-2.6,100.0,2.05,1.000,0.00000
2,NaN,15.0,-2.6,100.0,2.00,0.975,0.01146
3,NaN,15.0,-2.6,100.0,1.93,0.950,0.02222
4,8,15.0,-2.6,100.0,1.90,0.925,0.03184

In [29]:
data.columns

Index(['Unnamed: 0', 'Ambient temperature', 'Discharging current',
       'Depth of discharge', 'Average charging current', 'State of Health',
       'dSOH/dNeq'],
      dtype='object')

In [30]:
data = data.drop(['Unnamed: 0'], axis = 1)

In [31]:
data.head()

,Ambient temperature,Discharging current,Depth of discharge,Average charging current,State of Health,dSOH/dNeq
0,NaN,NaN,NaN,NaN,NaN,NaN
1,15.0,-2.6,100.0,2.05,1.000,0.00000
2,15.0,-2.6,100.0,2.00,0.975,0.01146
3,15.0,-2.6,100.0,1.93,0.950,0.02222
4,15.0,-2.6,100.0,1.90,0.925,0.03184

In [32]:
data = data.dropna()
data = data.reset_index(drop = True)

In [33]:
data.head()

,Ambient temperature,Discharging current,Depth of discharge,Average charging current,State of Health,dSOH/dNeq
0,15.0,-2.6,100.0,2.05,1.000,0.00000
1,15.0,-2.6,100.0,2.00,0.975,0.01146
2,15.0,-2.6,100.0,1.93,0.950,0.02222
3,15.0,-2.6,100.0,1.90,0.925,0.03184
4,15.0,-2.6,100.0,1.86,0.900,0.06180

In [34]:
data.shape

(252, 6)

In [37]:
%%shell
pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.9/dist-packages (1.2.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from scikit-learn) (1.22.4)

In [40]:
import sklearn

In [42]:
from sklearn.model_selection import train_test_split

In [49]:
training_data, testing_data = train_test_split(data, test_size = 0.3,random_state = 25)

In [50]:
training_data.head()

,Ambient temperature,Discharging current,Depth of discharge,Average charging current,State of Health,dSOH/dNeq
107,25.0,-5.2,100.0,1.73,0.800,0.04910
35,15.0,-5.2,50.0,2.16,0.800,0.12200
91,25.0,-7.8,100.0,1.92,0.975,0.02277
28,15.0,-5.2,50.0,2.20,0.975,0.01150
105,25.0,-5.2,100.0,1.78,0.850,0.03942

In [51]:
training_data.shape

(176, 6)

In [52]:
testing_data.shape

(76, 6)

In [53]:
testing_data.head(20)

,Ambient temperature,Discharging current,Depth of discharge,Average charging current,State of Health,dSOH/dNeq
153,40.0,-2.6,100.0,2.53,1.000,0.000000
200,10.0,-2.6,100.0,2.52,0.950,0.061800
66,25.0,-7.8,100.0,2.80,0.925,0.022300
229,25.0,-2.6,100.0,3.31,0.900,0.148000
224,10.0,-2.6,67.0,1.48,0.800,0.138150
134,25.0,-5.2,16.0,2.43,0.800,0.004989
4,15.0,-2.6,100.0,1.86,0.900,0.061800
149,40.0,-5.2,100.0,2.56,0.875,0.029460
97,25.0,-7.8,100.0,1.31,0.825,0.181300
202,10.0,-2.6,100.0,2.54,0.900,0.098900
6,15.0,-2.6,100.0,1.79,0.850,0.124130
12,15.0,-5.2,100.0,2.26,0.925,0.037760
148,40.0,-5.2,100.0,2.66,0.900,0.025260
191,10.0,-2.6,50.0,2.22,0.950,0.029421
163,40.0,-2.6,100.0,3.68,0.975,0.023850
19,15.0,-7.8,100.0,3.39,0.975,0.006200
75,25.0,-5.2,100.0,2.63,0.925,0.023830
164,40.0,-2.6,100.0,3.59,0.950,0.043180
142,40.0,-7.8,100.0,2.43,0.825,0.049100
56,25.0,-10.5,100.0,2.12,0.950,0.038500

In [58]:
training_X = training_data[['Ambient temperature', 'Discharging current',
       'Depth of discharge', 'Average charging current', 'State of Health']]

training_Y = training_data[['dSOH/dNeq']]


testing_X = testing_data[['Ambient temperature', 'Discharging current',
       'Depth of discharge', 'Average charging current', 'State of Health']]

testing_Y = testing_data[['dSOH/dNeq']]

In [59]:
training_X

,Ambient temperature,Discharging current,Depth of discharge,Average charging current,State of Health
107,25.0,-5.2,100.0,1.73,0.800
35,15.0,-5.2,50.0,2.16,0.800
91,25.0,-7.8,100.0,1.92,0.975
28,15.0,-5.2,50.0,2.20,0.975
105,25.0,-5.2,100.0,1.78,0.850
...,...,...,...,...,...
61,25.0,-10.5,100.0,1.41,0.825
143,40.0,-7.8,100.0,2.39,0.800
218,10.0,-2.6,67.0,1.59,0.950
62,25.0,-10.5,100.0,1.21,0.800
132,25.0,-5.2,16.0,2.46,0.850

In [61]:
training_Y

     dSOH/dNeq
107   0.049100
35    0.122000
91    0.022770
28    0.011500
105   0.039420
..         ...
61    0.298100
143   0.064135
218   0.022652
62    0.337100
132   0.004411

[176 rows x 1 columns]

In [62]:
testing_X

,Ambient temperature,Discharging current,Depth of discharge,Average charging current,State of Health
153,40.0,-2.6,100.0,2.530,1.000
200,10.0,-2.6,100.0,2.520,0.950
66,25.0,-7.8,100.0,2.800,0.925
229,25.0,-2.6,100.0,3.310,0.900
224,10.0,-2.6,67.0,1.480,0.800
...,...,...,...,...,...
68,25.0,-7.8,100.0,2.420,0.875
242,40.0,-3.9,100.0,2.298,0.800
133,25.0,-5.2,16.0,2.460,0.825
78,25.0,-5.2,100.0,2.400,0.850
85,25.0,-2.6,100.0,1.880,0.900

In [64]:
testing_Y

     dSOH/dNeq
153   0.000000
200   0.061800
66    0.022300
229   0.148000
224   0.138150
..         ...
68    0.030420
242   0.011891
133   0.004763
78    0.042500
85    0.015980

[76 rows x 1 columns]

In [65]:
model = LinearRegression()

In [66]:
model.fit(training_X, training_Y)
predict_Y = model.predict(testing_X)